/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ServicesObstetricsImport } from './routes/services.obstetrics'
import { Route as ServicesGynaecologyImport } from './routes/services.gynaecology'
import { Route as ServicesFertilityImport } from './routes/services.fertility'
import { Route as InfoUsefulLinksImport } from './routes/info.useful-links'
import { Route as InfoFeesImport } from './routes/info.fees'
import { Route as InfoAppointmentsImport } from './routes/info.appointments'

// Create/Update Routes

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ServicesObstetricsRoute = ServicesObstetricsImport.update({
  id: '/services/obstetrics',
  path: '/services/obstetrics',
  getParentRoute: () => rootRoute,
} as any)

const ServicesGynaecologyRoute = ServicesGynaecologyImport.update({
  id: '/services/gynaecology',
  path: '/services/gynaecology',
  getParentRoute: () => rootRoute,
} as any)

const ServicesFertilityRoute = ServicesFertilityImport.update({
  id: '/services/fertility',
  path: '/services/fertility',
  getParentRoute: () => rootRoute,
} as any)

const InfoUsefulLinksRoute = InfoUsefulLinksImport.update({
  id: '/info/useful-links',
  path: '/info/useful-links',
  getParentRoute: () => rootRoute,
} as any)

const InfoFeesRoute = InfoFeesImport.update({
  id: '/info/fees',
  path: '/info/fees',
  getParentRoute: () => rootRoute,
} as any)

const InfoAppointmentsRoute = InfoAppointmentsImport.update({
  id: '/info/appointments',
  path: '/info/appointments',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/info/appointments': {
      id: '/info/appointments'
      path: '/info/appointments'
      fullPath: '/info/appointments'
      preLoaderRoute: typeof InfoAppointmentsImport
      parentRoute: typeof rootRoute
    }
    '/info/fees': {
      id: '/info/fees'
      path: '/info/fees'
      fullPath: '/info/fees'
      preLoaderRoute: typeof InfoFeesImport
      parentRoute: typeof rootRoute
    }
    '/info/useful-links': {
      id: '/info/useful-links'
      path: '/info/useful-links'
      fullPath: '/info/useful-links'
      preLoaderRoute: typeof InfoUsefulLinksImport
      parentRoute: typeof rootRoute
    }
    '/services/fertility': {
      id: '/services/fertility'
      path: '/services/fertility'
      fullPath: '/services/fertility'
      preLoaderRoute: typeof ServicesFertilityImport
      parentRoute: typeof rootRoute
    }
    '/services/gynaecology': {
      id: '/services/gynaecology'
      path: '/services/gynaecology'
      fullPath: '/services/gynaecology'
      preLoaderRoute: typeof ServicesGynaecologyImport
      parentRoute: typeof rootRoute
    }
    '/services/obstetrics': {
      id: '/services/obstetrics'
      path: '/services/obstetrics'
      fullPath: '/services/obstetrics'
      preLoaderRoute: typeof ServicesObstetricsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/info/appointments': typeof InfoAppointmentsRoute
  '/info/fees': typeof InfoFeesRoute
  '/info/useful-links': typeof InfoUsefulLinksRoute
  '/services/fertility': typeof ServicesFertilityRoute
  '/services/gynaecology': typeof ServicesGynaecologyRoute
  '/services/obstetrics': typeof ServicesObstetricsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/info/appointments': typeof InfoAppointmentsRoute
  '/info/fees': typeof InfoFeesRoute
  '/info/useful-links': typeof InfoUsefulLinksRoute
  '/services/fertility': typeof ServicesFertilityRoute
  '/services/gynaecology': typeof ServicesGynaecologyRoute
  '/services/obstetrics': typeof ServicesObstetricsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/info/appointments': typeof InfoAppointmentsRoute
  '/info/fees': typeof InfoFeesRoute
  '/info/useful-links': typeof InfoUsefulLinksRoute
  '/services/fertility': typeof ServicesFertilityRoute
  '/services/gynaecology': typeof ServicesGynaecologyRoute
  '/services/obstetrics': typeof ServicesObstetricsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/info/appointments'
    | '/info/fees'
    | '/info/useful-links'
    | '/services/fertility'
    | '/services/gynaecology'
    | '/services/obstetrics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/info/appointments'
    | '/info/fees'
    | '/info/useful-links'
    | '/services/fertility'
    | '/services/gynaecology'
    | '/services/obstetrics'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/info/appointments'
    | '/info/fees'
    | '/info/useful-links'
    | '/services/fertility'
    | '/services/gynaecology'
    | '/services/obstetrics'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  InfoAppointmentsRoute: typeof InfoAppointmentsRoute
  InfoFeesRoute: typeof InfoFeesRoute
  InfoUsefulLinksRoute: typeof InfoUsefulLinksRoute
  ServicesFertilityRoute: typeof ServicesFertilityRoute
  ServicesGynaecologyRoute: typeof ServicesGynaecologyRoute
  ServicesObstetricsRoute: typeof ServicesObstetricsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  InfoAppointmentsRoute: InfoAppointmentsRoute,
  InfoFeesRoute: InfoFeesRoute,
  InfoUsefulLinksRoute: InfoUsefulLinksRoute,
  ServicesFertilityRoute: ServicesFertilityRoute,
  ServicesGynaecologyRoute: ServicesGynaecologyRoute,
  ServicesObstetricsRoute: ServicesObstetricsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/info/appointments",
        "/info/fees",
        "/info/useful-links",
        "/services/fertility",
        "/services/gynaecology",
        "/services/obstetrics"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/info/appointments": {
      "filePath": "info.appointments.tsx"
    },
    "/info/fees": {
      "filePath": "info.fees.tsx"
    },
    "/info/useful-links": {
      "filePath": "info.useful-links.tsx"
    },
    "/services/fertility": {
      "filePath": "services.fertility.tsx"
    },
    "/services/gynaecology": {
      "filePath": "services.gynaecology.tsx"
    },
    "/services/obstetrics": {
      "filePath": "services.obstetrics.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
